
/**************************************************************
 *	
 *	freddie, 8 bit, 8000Hz,
 *	1 channel, 25799 bytes/channel
 *	Total Size: 1 * 25799 + 4 (header) = 25843 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Casey\Documents\NetBeansProjects\JohnSmith_FinalProject\freddie.wav
 *	Time-stamp: Mon Dec 05 09:13:57 2011
 *	
 **************************************************************/

#ifndef __FREDDIEH__
#define __FREDDIEH__

#define FREDDIEFREQ 8000
#define FREDDIELEN 25799

extern const unsigned char freddie[25799];

#endif /* __FREDDIEH__ */
