
/**************************************************************
 *	
 *	photon, 8 bit, 11025Hz,
 *	1 channel, 9067 bytes/channel
 *	Total Size: 1 * 9067 + 4 (header) = 9111 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Casey\Documents\NetBeansProjects\JohnSmith_FinalProject\photon.wav
 *	Time-stamp: Mon Dec 05 09:21:26 2011
 *	
 **************************************************************/

#ifndef __PHOTONH__
#define __PHOTONH__

#define PHOTONFREQ 11025
#define PHOTONLEN 9067

extern const unsigned char photon[9067];

#endif /* __PHOTONH__ */
